### ISSUE TITLE
joined cohort does not respect return expectations

### ISSUE THREAD

**Issue by ccunningham101** [iaindillingham/cohort-joiner#28] opened 2022-04-04 14:30 UTC
Left hand cohorts and right hand cohort are generated with separate generate_cohort actions, so they have populations with different patient IDs
Joining the two cohorts will lead to a joined file with many more missing values for the attribute in the rhs cohort than the specified return_expectations
This could lead to an analyst having to write code specifically for dummy data handling that would not be required on real data

```
    ethnicity=patients.categorised_as(
        {
            "missing": "DEFAULT",
            "British": "eth='1'",
            "Irish": "eth='2'",
             ....
        }, 
        return_expectations={
                "rate": "universal",
                 ....
        }
    )
```
For example when using "categorised_as" on ethnicity in the rhs cohort, all missing values will be set to the text string "missing", and there should not be any "" values
But when there is a patient id in the lhs cohort that is not matched in the rhs cohort, its ethnicity will be set to ""

It might not be feasible/worth the effort on the cohort-extractor, but if generate cohort could take in a list of IDs to use? 

@LindaNab also had this issue

**Comment by iaindillingham** [comment] 2022-04-04 15:14
This issue isn't with cohort-joiner, which simply joins whatever cohorts it's given. However, it clearly causes confusion. I'll start by documenting it in the cohort-joiner README and in the OpenSAFELY documentation.

We could think of generating dummy data as an integration test: we pass dummy data to our code to check that it executes correctly, so that when we pass real data to our code, we can be reasonably sure that it will also execute correctly. With dummy data generated by the expectations framework, unfortunately, that means our intuition is incorrect:  we expect to see more results than we see, because of the nature of dummy data generated by the expectations framework.

If we wanted to preserve our intuition, then we could generate dummy data ourselves (i.e. not using the expectations framework) and then pass it to `generate_cohort` with the `--dummy-data-file` argument. However, doing so would mean writing more code (and encountering many of the issues that motivated the development of cohort-joiner) and also making the project pipeline aware of when it was running in "dummy data" mode and "real data" mode.

**Comment by ccunningham101** [comment] 2022-04-05 08:00
Yes not actually an issue with cohort joiner (it was also an issue with the previous join_ethnicity approach)
But I agree documentation would be helpful for now!

**Comment by iaindillingham** [comment] 2022-04-05 09:28
I'm going to row back on documenting this issue in the OpenSAFELY documentation and instead document it in the cohort-joiner README. This is because the former should be a pointer to, and not a duplicate of, the latter. I can't think of a reasonable workaround, so haven't included the `--dummy-data-file` argument.

**Closed as completed** 2022-04-05 10:51 UTC
